### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by dkvc** [dkvc/pwcode#24]

**Comment by Javeed9** [comment]
Hello, how can i help?

**Comment by Aakashjammula** [comment]
> 

There is  branch for readme called"add-readme" ,  we can collaborate on it.

**Comment by Aakashjammula** [comment]
if you want to work on this issue, then I can assign you.

**Comment by Javeed9** [comment]
Ha yes, I can work on this issue

**Comment by dkvc** [comment]
> Ha yes, I can work on this issue

While I'm sure @Aakashjammula can work you through the process of creating README, here are high-level overview of process.

The README currently consists of 5 sections:
1. **Introduction:** I already finished working on most of it. If you have any ideas to add, let us know.
2. **Usage:** This section describes to a user on how to add pwcode feed to their feeder app. While writing this reply, I got an idea to linking to corresponding feeder apps as (this is better than asking the user to set up on their own):
[![Rss](https://img.shields.io/badge/rss-F88900?style=for-the-badge&logo=rss&logoColor=white)](https://pwcode.onrender.com/atom)
3. **Setting up Local Dev Environment:** There are two ways to set up local dev environment - Dockerfile (this must be updated soon) or locally. The steps to set up local dev environment if Docker is used and locally must be seperated.
**Conflict:** There is a currently a conflict on whether this section should be under **README.md** or **CONTRIBUTING.md**. If the section is in **CONTRIBUTING.md**, then the corresponding link must be written under *Contributing Guidelines*.
4. **Credits:** This project is possible with PapersWithCode own API, FastAPI, pendulum, other libraries and all collaborators working on the project. Be sure to credit them without which this project wouldn't have completed fast.
5. **Contribuing:** This section links to **Contributing Guidelines (CONTRIBUTING.md)** and **Code of Conduct (CODE_OF_CONDUCT.md)** of project describing contributors adhering to Code of Coduct and follow the Contributing Guidelines. (I might think of making this by adding CLA and linking it).
**Conflict:** There is a conflict whether **this section** or **Contributing Guidelines** should describe on how to contribute to this project. Currently, I think it is best suited under Contributing Guidelines. If you have any other idea, you can let us know.

@Javeed9 
You can try splitting up sections between yourself and @Aakashjammula. In case of any issues, you can tag me or @Aakashjammula. The work is in progress on [fix-readme](https://github.com/dkvc/pwcode/tree/add-readme) branch of this repository. You can fork this repository and use your fork to push changes. Let us know in case you are dropping the issue.

Thank you for working on this issue!

**Comment by dkvc** [comment]
@Aakashjammula @Javeed9 Progress check. Are you still working on this issue?

**Comment by Javeed9** [comment]
@dkvc Yes!, had some troubles with pc, now it's okay, i will update progress shortly

**Comment by dkvc** [comment]
>     5. **Contributing:** This section links to **Contributing Guidelines (CONTRIBUTING.md)** and **Code of Conduct (CODE_OF_CONDUCT.md)** of project describing contributors adhering to Code of Coduct and follow the Contributing Guidelines. (I might think of making this by adding CLA and linking it).
>        **Conflict:** There is a conflict whether **this section** or **Contributing Guidelines** should describe on how to contribute to this project. Currently, I think it is best suited under Contributing Guidelines. If you have any other idea, you can let us know.

Due to time constraints, **Contributing Guidelines** and **Code of Conduct** are no longer considered under **README.md**. And **CONTRIBUTING.md** now includes only on setting up local dev environment.
